### ISSUE TITLE
Plugin has no effect (10.14.6)

### ISSUE THREAD

**Issue by Shnub** [saagarjha/DetailsViewer#2]
I appreciate the new release, thank you. Now I don't get an error from Mail when DetailsViewer is in the Mail bundles folder (#1). However, the plugin doesn't seem to do anything. I still have to click "Details" in every message, and I get no tooltips in the message list. Any idea why? I'm on 10.14.6/Mail 12.4 now.

**Comment by saagarjha** [comment]
The plugin uses new APIs from Catalina, so it will only load for those versions of Mail :(

**Comment by Shnub** [comment]
Dangit. I won't be "upgrading" to Catalina anytime soon. Too bad!
